-- ============================================================================
--  PKG_IR_DADOS — lê 100% das linhas de um Interactive Report do APEX
--  RESPEITANDO O FILTRO DA TELA (inclusive o do botão Ações), porque roda NA
--  MESMA SESSÃO do usuário — via um Processo de Aplicação On-Demand (AJAX
--  Callback) chamado pelo widget com apex.server.process.
--
--  Diferença para a tentativa anterior (ORDS): o ORDS abre uma SESSÃO NOVA
--  (create_session) e por isso enxerga só o relatório padrão/salvo — nunca o
--  filtro ad-hoc da tela. Aqui a execução NASCE na sessão do usuário logado,
--  então apex_ir.get_last_viewed_report_id + apex_region.open_query_context
--  trazem exatamente a visão que ele está vendo (baseado no exemplo que já
--  funcionava — FNCT_GERAR_CSV_IR).
--
--  MULTI-SCHEMA: este pacote e a tabela precisam existir no PARSING SCHEMA do
--  app (ex.: RHNATCORP), pois apex_exec/apex_region rodam no contexto do app.
--  Crie em cada schema de cliente. O Processo On-Demand (PRC_DADOS_IR) é por
--  app — injetado em lote depois (ele só chama pkg_ir_dados.prc_responder_ir).
--
--  Contrato do JSON de coleta (o widget depende):
--    { "ok":true, "id":N, "total_linhas":N, "colunas":[...], "amostra":[[...],...] }
--    { "ok":false, "erro":"..." }
-- ============================================================================

-- ----------------------------------------------------------------------------
--  1) TABELA de armazenamento do CSV completo (fonte do download por id).
--     Retenção: limpe linhas antigas por um job (ex.: criado_em < sysdate-1).
-- ----------------------------------------------------------------------------
-- create table ai_ir_dados_log (
--   id            number generated by default on null as identity primary key,
--   criado_em     timestamp     default systimestamp,
--   app_id        number,
--   page_id       number,
--   region_id     number,
--   ir_report_id  number,
--   app_user      varchar2(255),
--   session_id    varchar2(255),
--   total_linhas  number,
--   csv           clob,
--   status        varchar2(20)  default 'OK'
-- );

-- ----------------------------------------------------------------------------
--  2) SPEC
-- ----------------------------------------------------------------------------
create or replace package pkg_ir_dados as

  -- Núcleo: lê o IR (app/página/região) NA SESSÃO ATUAL (respeita o filtro do
  -- Ações), grava o CSV completo em ai_ir_dados_log e devolve o JSON de coleta
  -- (metadados + amostra). O CSV grande NÃO vai no JSON — vem pelo id (download).
  --  p_region: static id | "R<region_id>" | número do region_id | nome da região.
  --  p_items : JSON de application items — usado SÓ no caminho ORDS/catálogo
  --            (Fase 2). In-session passa null (não sobrescreve o estado do user).
  function fnct_ir_dados_json(
    p_app_id          in number,
    p_page_id         in number,
    p_region          in varchar2,
    p_amostra_linhas  in number default 100000, -- amostra = TODAS as linhas até este teto
    p_com_csv         in boolean default false,  -- montar o CSV completo (download por id)? padrão NÃO — não é consumido e dobra o custo
    p_items           in clob    default null
  ) return clob;

  -- Shim do Processo On-Demand PRC_DADOS_IR (chamado via apex.server.process):
  --   x01=app  x02=page  x03=regiao                 → JSON de coleta
  --   x04='CSV' x05=id                              → CSV cru completo (download)
  procedure prc_responder_ir;

end pkg_ir_dados;
/

-- ----------------------------------------------------------------------------
--  3) BODY
-- ----------------------------------------------------------------------------
create or replace package body pkg_ir_dados as

  -- Seta application items a partir de um JSON (só quando informado — Fase 2/ORDS).
  procedure p_set_items(p_items in clob) is
  begin
    if p_items is null then return; end if;
    if json_value(p_items,'$.P_USUARIO')        is not null then apex_util.set_session_state('P_USUARIO',        json_value(p_items,'$.P_USUARIO')); end if;
    if json_value(p_items,'$.P_EMPRESA_USER')   is not null then apex_util.set_session_state('P_EMPRESA_USER',   json_value(p_items,'$.P_EMPRESA_USER')); end if;
    if json_value(p_items,'$.P_MATRICULA_USER') is not null then apex_util.set_session_state('P_MATRICULA_USER', json_value(p_items,'$.P_MATRICULA_USER')); end if;
    if json_value(p_items,'$.P_PERFIL')         is not null then apex_util.set_session_state('P_PERFIL',         json_value(p_items,'$.P_PERFIL')); end if;
    if json_value(p_items,'$.P_BASE')           is not null then apex_util.set_session_state('P_BASE',           json_value(p_items,'$.P_BASE')); end if;
    if json_value(p_items,'$.P_PAINEL')         is not null then apex_util.set_session_state('P_PAINEL',         json_value(p_items,'$.P_PAINEL')); end if;
  exception when others then null; -- não derruba a coleta por causa de um item
  end p_set_items;

  -- Limpa o VALOR de uma célula para consumo por IA/CSV: remove tags HTML (colunas
  -- de imagem/link — ex.: FOTO com <img ...> — viram texto puro/vazio) e comprime
  -- espaços. Texto puro passa intacto. Reduz MUITO o token de colunas renderizadas.
  function f_texto(p in varchar2) return varchar2 is
    v varchar2(32767) := p;
  begin
    if v is null then return null; end if;
    -- Só paga o regex de HTML quando há tag (a maioria das células é texto puro).
    -- Saída idêntica: em texto sem '<', o regexp_replace seria no-op de qualquer forma.
    if instr(v, '<') > 0 then v := regexp_replace(v, '<[^>]+>', ' '); end if;
    return trim(regexp_replace(v, '[[:space:]]{2,}', ' '));
  end f_texto;

  -- Milissegundos entre dois timestamps — usado para medir o desempenho da coleta
  -- (separar o custo da CONSULTA do custo da SERIALIZAÇÃO das linhas).
  function ms_entre(a in timestamp, b in timestamp) return number is
    d interval day to second := b - a;
  begin
    return extract(day    from d) * 86400000
         + extract(hour   from d) * 3600000
         + extract(minute from d) * 60000
         + extract(second from d) * 1000;
  end ms_entre;

  -- Resolve o region_id: "R123"/número → id; senão static id; senão nome.
  function f_region_id(p_app in number, p_page in number, p_region in varchar2) return number is
    l_id number;
  begin
    if regexp_like(nvl(p_region,'x'), '^R[0-9]+$') then return to_number(substr(p_region, 2)); end if;
    if regexp_like(nvl(p_region,'x'), '^[0-9]+$')  then return to_number(p_region);            end if;
    select region_id into l_id from (
       select region_id from apex_application_page_regions
        where application_id = p_app and page_id = p_page and upper(static_id)   = upper(p_region)
       union
       select region_id from apex_application_page_regions
        where application_id = p_app and page_id = p_page and upper(region_name) = upper(p_region)
    ) where rownum = 1;
    return l_id;
  end f_region_id;

  function fnct_ir_dados_json(
    p_app_id          in number,
    p_page_id         in number,
    p_region          in varchar2,
    p_amostra_linhas  in number default 100000, -- amostra = TODAS as linhas até este teto
    p_com_csv         in boolean default false,  -- montar o CSV completo (download por id)? padrão NÃO — não é consumido e dobra o custo
    p_items           in clob    default null
  ) return clob is
    l_region_id  number;
    l_report_id  number;
    l_ctx        apex_exec.t_context;
    l_col_count  pls_integer;
    l_col        apex_exec.t_column;
    -- Metadado das colunas (tipo) lido UMA vez — invariante por linha. Antes,
    -- apex_exec.get_column era chamado por célula de cada linha (milhares de vezes).
    type t_tipos is table of pls_integer index by pls_integer;
    l_col_tipo   t_tipos;
    l_line       varchar2(32767);
    l_cell       varchar2(32767);
    l_json       varchar2(32767);  -- buffer da serialização JSON manual (descarregado no CLOB em blocos)
    l_val        varchar2(32767);  -- valor JSON de UMA célula (já escapado por apex_json.stringify)
    l_num        number;
    l_date       date;
    l_ts         timestamp;
    l_csv        clob;
    l_total      number := 0;
    l_id         number;
    l_out        clob;
    -- Medição de desempenho (ms) — separa CONSULTA (execução+ordenação no banco)
    -- de SERIALIZAÇÃO (montar CSV/JSON célula a célula) e da GRAVAÇÃO do CSV.
    l_t0         timestamp;
    l_t_loop0    timestamp;
    l_t_ins0     timestamp;
    l_ms_abrir   number := 0;   -- open_query_context + contagem de colunas
    l_ms_1a      number := 0;   -- até a 1ª linha (execução + ORDER BY da consulta)
    l_ms_loop    number := 0;   -- laço inteiro (buscar linhas + montar CSV/JSON)
    l_ms_gravar  number := 0;   -- insert + commit do CSV completo
    l_ms_total   number := 0;
    l_primeira   boolean := true;
  begin
    l_t0 := systimestamp;
    p_set_items(p_items);                                   -- só no caminho ORDS

    l_region_id := f_region_id(p_app_id, p_page_id, p_region);
    -- Report da ÚLTIMA visão do usuário (traz os filtros/apresentação correntes).
    l_report_id := apex_ir.get_last_viewed_report_id(p_page_id => p_page_id, p_region_id => l_region_id);
    -- Contexto de dados JÁ com os filtros do IR (é aqui que o filtro do Ações entra).
    l_ctx := apex_region.open_query_context(
               p_page_id      => p_page_id,
               p_region_id    => l_region_id,
               p_component_id => l_report_id,
               p_view_mode    => apex_ir.c_view_report);

    l_col_count := apex_exec.get_column_count(l_ctx);
    l_ms_abrir  := ms_entre(l_t0, systimestamp);

    if p_com_csv then dbms_lob.createtemporary(l_csv, true); end if;
    dbms_lob.createtemporary(l_out, true);

    -- SERIALIZAÇÃO MANUAL (buffer VARCHAR2 → CLOB), com escape via apex_json.stringify
    -- (função PURA). Antes era apex_json.write POR CÉLULA (~colunas×linhas ≈ dezenas de
    -- milhares de chamadas ao CLOB) — o gargalo dos ~65s. Agora concatenamos em VARCHAR2
    -- e descarregamos no CLOB em blocos de ~30k. apex_json.stringify garante JSON válido.
    l_json := '{"ok":true,"colunas":[';

    -- Cabeçalho: colunas (JSON) + tipos (lidos UMA vez) + linha de colunas do CSV.
    l_line := null;
    for i in 1 .. l_col_count loop
      l_col := apex_exec.get_column(l_ctx, i);
      l_col_tipo(i) := l_col.data_type;               -- cacheia o tipo p/ o laço de linhas
      if length(l_json) > 30000 then dbms_lob.writeappend(l_out, length(l_json), l_json); l_json := null; end if;
      if i > 1 then l_json := l_json || ','; end if;
      l_json := l_json || apex_json.stringify(l_col.name);
      if p_com_csv then
        if i > 1 then l_line := l_line || ';'; end if;
        l_line := l_line || '"' || replace(l_col.name, '"', '""') || '"';
      end if;
    end loop;
    l_json := l_json || '],"amostra":[';
    if p_com_csv then dbms_lob.writeappend(l_csv, length(l_line) + 1, l_line || chr(10)); l_line := null; end if;

    -- Linhas: array-de-arrays "amostra" até p_amostra_linhas (cobre 100% dos casos comuns).
    l_t_loop0 := systimestamp;
    while apex_exec.next_row(l_ctx) loop
      -- 1ª linha só volta depois da consulta executar e ORDENAR: isola o custo do banco.
      if l_primeira then l_ms_1a := ms_entre(l_t_loop0, systimestamp); l_primeira := false; end if;
      l_total := l_total + 1;
      -- Passou do teto da amostra e sem CSV: só CONTA (total exato), sem tocar nas células.
      if l_total > p_amostra_linhas and not p_com_csv then continue; end if;
      l_line := null;

      if l_total <= p_amostra_linhas then
        -- descarrega o buffer se estiver cheio ANTES de abrir a linha
        if length(l_json) > 30000 then dbms_lob.writeappend(l_out, length(l_json), l_json); l_json := null; end if;
        l_json := l_json || case when l_total > 1 then ',[' else '[' end;
      end if;

      for i in 1 .. l_col_count loop
        begin
          case l_col_tipo(i)
            when apex_exec.c_data_type_number then
              l_num  := apex_exec.get_number(l_ctx, i);
              l_cell := case when l_num is null then null else to_char(l_num) end;
            when apex_exec.c_data_type_date then
              l_date := apex_exec.get_date(l_ctx, i);
              l_cell := case when l_date is null then null else to_char(l_date, 'DD/MM/RRRR') end;
            when apex_exec.c_data_type_timestamp then
              l_ts   := apex_exec.get_timestamp(l_ctx, i);
              l_cell := case when l_ts is null then null else to_char(l_ts, 'DD/MM/RRRR HH24:MI:SS') end;
            else
              l_cell := f_texto(apex_exec.get_varchar2(l_ctx, i));
          end case;
        exception when others then l_cell := null; -- célula problemática vira vazio
        end;

        if l_total <= p_amostra_linhas then
          -- Valor JSON: null OU string escapada (capada em 8000 p/ caber no buffer; o
          -- servidor já trunca a célula em 300 chars, então nada útil se perde).
          l_val := case when l_cell is null then 'null' else apex_json.stringify(substr(l_cell, 1, 8000)) end;
          if length(l_json) + length(l_val) + 2 > 32000 then dbms_lob.writeappend(l_out, length(l_json), l_json); l_json := null; end if;
          if i > 1 then l_json := l_json || ','; end if;
          l_json := l_json || l_val;
        end if;
        if p_com_csv then
          if i > 1 then l_line := l_line || ';'; end if;
          l_line := l_line || '"' || replace(nvl(l_cell, ''), '"', '""') || '"';
        end if;
      end loop;

      if l_total <= p_amostra_linhas then l_json := l_json || ']'; end if;
      if p_com_csv then dbms_lob.writeappend(l_csv, length(l_line) + 1, replace(l_line, '\', '\\') || chr(10)); end if;
    end loop;
    l_ms_loop := ms_entre(l_t_loop0, systimestamp);
    apex_exec.close(l_ctx);

    l_json := l_json || ']'; -- fecha "amostra"
    dbms_lob.writeappend(l_out, length(l_json), l_json); l_json := null;

    -- Registro/id (auditoria + fonte do download quando p_com_csv). csv NULL quando off.
    l_t_ins0 := systimestamp;
    insert into ai_ir_dados_log (app_id, page_id, region_id, ir_report_id, app_user, session_id, total_linhas, csv, status)
    values (p_app_id, p_page_id, l_region_id, l_report_id, v('APP_USER'), v('APP_SESSION'), l_total, l_csv, 'OK')
    returning id into l_id;
    commit;
    l_ms_gravar := ms_entre(l_t_ins0, systimestamp);

    -- id + total + tempos_ms (números → concatenação direta, sem escape). Fecha o objeto raiz.
    --   serializar = loop_total - ate_primeira_linha (montar o JSON; + CSV se p_com_csv)
    l_ms_total := ms_entre(l_t0, systimestamp);
    l_json := ',"id":' || l_id
      || ',"total_linhas":' || l_total
      || ',"tempos_ms":{"abrir_ctx":' || round(l_ms_abrir)
      || ',"ate_primeira_linha":' || round(l_ms_1a)
      || ',"serializar":' || round(greatest(l_ms_loop - l_ms_1a, 0))
      || ',"loop_total":' || round(l_ms_loop)
      || ',"gravar":' || round(l_ms_gravar)
      || ',"total":' || round(l_ms_total)
      || '}}';
    dbms_lob.writeappend(l_out, length(l_json), l_json);
    if p_com_csv then begin dbms_lob.freetemporary(l_csv); exception when others then null; end; end if;
    return l_out;

  exception
    when others then
      -- NÃO usar apex_exec.is_open (não existe no 19.2 — você já tinha comentado no
      -- seu exemplo): só tenta fechar, engolindo erro se já estiver fechado.
      begin apex_exec.close(l_ctx); exception when others then null; end;
      begin apex_json.free_output; exception when others then null; end;
      return '{"ok":false,"erro":"' || replace(replace(substr(sqlerrm, 1, 300), '\', '/'), '"', '''') || '"}';
  end fnct_ir_dados_json;

  procedure prc_responder_ir is
    l_mode varchar2(20) := upper(nvl(apex_application.g_x04, ''));
    l_json clob;
    l_csv  clob;
    l_len  integer;
    l_off  integer := 1;
    l_amt  integer := 8000; -- pedaço < 32767 p/ htp.prn (VARCHAR2), seguro c/ acentos
  begin
    -- Download do CSV completo por id (x04='CSV', x05=id).
    if l_mode = 'CSV' then
      select csv into l_csv from ai_ir_dados_log where id = to_number(apex_application.g_x05);
      l_len := dbms_lob.getlength(l_csv);
      while l_off <= nvl(l_len, 0) loop
        htp.prn(dbms_lob.substr(l_csv, l_amt, l_off));
        l_off := l_off + l_amt;
      end loop;
      return;
    end if;

    -- Coleta: devolve o JSON (metadados + amostra), emitido em pedaços.
    l_json := pkg_ir_dados.fnct_ir_dados_json(
                p_app_id  => to_number(apex_application.g_x01),
                p_page_id => to_number(apex_application.g_x02),
                p_region  => apex_application.g_x03);
    l_len := dbms_lob.getlength(l_json);
    while l_off <= nvl(l_len, 0) loop
      htp.prn(dbms_lob.substr(l_json, l_amt, l_off));
      l_off := l_off + l_amt;
    end loop;
  exception when others then
    htp.prn('{"ok":false,"erro":"' || replace(substr(sqlerrm, 1, 300), '"', '''') || '"}');
  end prc_responder_ir;

end pkg_ir_dados;
/

-- ----------------------------------------------------------------------------
--  4) PROCESSO ON-DEMAND "PRC_DADOS_IR" (por app) — crie em UM app pelo Builder:
--     Shared Components → Application Processes → Create
--        Name           : PRC_DADOS_IR
--        Point          : On Demand (Run this application process when requested…)
--        Type           : PL/SQL
--        PL/SQL Code     : begin pkg_ir_dados.prc_responder_ir; end;
--     (Depois exporte o app e me mande o bloco wwv_flow_api.create_flow_process
--      que o APEX gerar — é o que eu replico no script de lote pros demais apps.)
-- ----------------------------------------------------------------------------
