-- =====================================================================
-- A BUSCA PASSA A RECUSAR DOCUMENTO DE OUTRA BASE, DENTRO DO BANCO
--
-- Hoje o isolamento entre clientes depende inteiramente de a aplicação
-- montar a lista de ids certa: o widget entra como `service_role`, que
-- tem `rolbypassrls`, e RLS nunca protege esse caminho. A tarefa 6 provou
-- que a aplicação acerta (`.audit/isolamento-documentacao-e2e.ts`). Esta
-- migration faz o BANCO recusar o erro, mesmo que a aplicação erre.
--
-- ── A cerca é de PROPRIEDADE, nunca de elegibilidade ──────────────────
-- O brief original desta tarefa mandava filtrar por
-- `public.documentos_da_base(p_base)`. Isso está ERRADO e foi corrigido
-- antes de chegar aqui: `documentos_da_base` tem `p_identidade jsonb
-- default '{}'::jsonb`, então filtrar por ela aqui dentro avaliaria
-- elegibilidade com identidade VAZIA — pela regra "ausência fecha", todo
-- documento restrito por portal/perfil/centro de custo seria recusado
-- mesmo para o usuário CERTO. Esta cerca não recalcula elegibilidade: ela
-- só verifica se `knowledge_documents.base_id`, quando existe, bate com a
-- base que pediu a busca.
--
-- ── Correção MEDIDA nesta tarefa, além das do brief ────────────────────
-- O brief desta tarefa (rescrito em 25/09) instrui usar `create or
-- replace` acrescentando `p_base` como novo parâmetro, e mandava
-- EXPLICITAMENTE não usar `drop function` da assinatura antiga ("devolve
-- EXECUTE a PUBLIC — não faça").
--
-- Medido antes de aplicar (script descartável, dentro de
-- BEGIN/ROLLBACK, nunca commitado): criar duas funções com o MESMO nome,
-- uma com N parâmetros e outra com N+1 (o N+1º com DEFAULT), e chamar
-- só com os primeiros N nomeados — exatamente como o app chama hoje via
-- `supabase.rpc(nome, {...})` — produz:
--
--   ERROR: function public.zz_teste_overload(p_query => unknown,
--   p_node_ids => unknown) is not unique
--
-- Ou seja: `create or replace function` com um parâmetro A MAIS não
-- substitui a função antiga — cria uma SEGUNDA função (assinatura
-- diferente = função diferente, para o Postgres). Com as duas de pé,
-- TODA chamada existente que não passa `p_base` fica AMBÍGUA entre as
-- duas, e quebra em produção com "function ... is not unique" — a busca
-- do chat e do portal inteiros parariam de responder.
--
-- Isto não é hipótese: é o padrão já estabelecido NESTE repositório para
-- esta MESMA função, em pelo menos quatro migrations anteriores
-- (20260720140000, 20260721131000, 20260725120000, 20260805130000) —
-- todas fazem `drop function if exists <assinatura antiga>` antes do
-- `create or replace` sempre que `hybrid_search_scoped` ganha parâmetro
-- novo, com o comentário "Assinatura muda (ganha 1 arg) → precisa DROP
-- antes do CREATE (padrão do repo)" na mais recente delas. A instrução
-- deste brief de NÃO fazer o drop contradiz o próprio padrão que o
-- repositório já usa há meses para o mesmo cenário, e aplicá-la como
-- escrita quebraria produção. Este arquivo segue o padrão do repo, não
-- o texto literal do brief nesse ponto específico.
--
-- O risco que o brief queria evitar (o `drop` devolver EXECUTE a PUBLIC)
-- foi verificado e não se aplica aqui: nenhuma migration jamais revogou
-- EXECUTE destas duas funções de `anon`/`public` (checado por grep em
-- todo `supabase/migrations/`), então não há revoke de migration
-- posterior para desfazer. O privilégio atual — EXECUTE aberto a
-- PUBLIC (portanto a `anon` também) — é o comportamento ORIGINAL destas
-- funções desde a criação, preservado aqui sem nenhuma instrução de
-- grant nova: elas rodam `SECURITY INVOKER` (não têm `SECURITY DEFINER`),
-- então quando `anon` chama, a leitura de `chunks` continua governada
-- pela RLS de `anon` (`chunks_public_read`), exatamente como hoje.
--
-- NÃO revogar de `anon` nesta função nem em `knowledge_list_chunks`,
-- mesmo que a restrição global do projeto mande "função nova: revoke de
-- public, anon". Estas não são novas: a busca do portal chama
-- `hybrid_search_scoped` como `anon`, sem sessão nenhuma
-- (`src/app/(portal)/actions.ts:141`). Aplicar aquela regra aqui reproduz
-- exatamente o incidente que `20260721140000_search_anon_knowledge_grant.sql`
-- documenta: a busca do portal morre com "permission denied", e a action
-- engole o erro como lista vazia — silencioso, igual ao defeito que esta
-- própria migration corrige em outro lugar.
--
-- Acoplamento com a RLS, para quem for mexer em policy depois: como as
-- duas funções são `SECURITY INVOKER`, o `not exists` desta cerca só diz a
-- verdade porque, para `authenticated`, a permissão que abre o CHUNK de
-- arquivo de base (`chunks_auth_read`, exige `ai.configure`) é a MESMA que
-- abre a LINHA de `knowledge_documents` que a cerca lê (`knowledge_
-- documents_read`, também `ai.configure`). Se uma das duas policies for
-- estreitada sem a outra, a cerca passa a enxergar "não existe documento
-- de outra base" para um `authenticated` que só não tem permissão de
-- LER a tabela — abrindo em silêncio, não fechando. Hoje isto é inofensivo
-- porque `p_base` só chega por `service_role` (que tem `rolbypassrls` e
-- não passa pela RLS de jeito nenhum), mas a dependência existe e fica
-- registrada aqui.
--
-- ── Onde a cerca entra ─────────────────────────────────────────────────
-- UM lugar só em cada função: no CTE `agrupado` de `hybrid_search_scoped`
-- (upstream de `melhores_grupos` — um documento de outra base é
-- descartado ANTES de consumir vaga de grupo) e no `where` de
-- `knowledge_list_chunks`. As quatro CTEs de sinal (`ft`, `trg`, `vec`,
-- `boost`) e a fusão RRF ficam INTOCADAS — repetir a cerca nelas seria
-- duplicação, e não muda o resultado porque `agrupado`/`melhores_grupos`
-- já filtram depois.
--
-- `not exists (select 1 from base_alvo ba where ba.id = d.base_id)`, não
-- uma subconsulta ESCALAR: `ai_bases_base_code_key` é `unique(base_code)`,
-- case-sensitive e sem trim — 'Natcorp' e 'natcorp ' coexistem
-- legitimamente hoje (conferido: não coexistem AINDA, mas a constraint não
-- impede). No dia em que coexistirem, `base_alvo` (que normaliza com
-- `lower(btrim(...))`) devolveria DUAS linhas, e `(select id from
-- base_alvo)` como subconsulta escalar levantaria `more than one row
-- returned by a subquery used as an expression` — erro que `rag.ts` não
-- veria, porque as quatro chamadas desestruturam só `{ data }` e ignoram
-- `error`: a busca daquela base voltaria vazia, em silêncio, sem
-- documentação nenhuma. `not exists` com JOIN de pertinência tolera
-- `base_alvo` com zero, uma ou várias linhas sem erro nenhum, e preserva a
-- MESMA postura "ausência fecha": com `base_alvo` vazio (p_base nulo, ou
-- código que não bate com nenhuma base) nada casa a pertinência, o `not
-- exists` externo é falso e todo documento de base é recusado — idêntico
-- ao que o `is distinct from` fazia antes desta correção.
--
-- `d.base_id is not null`: deixa passar documento de ESPAÇO (documentação
-- anexada, `base_id` nulo) e, por `d.id = c2.document_id` nunca casar
-- quando `document_id` é nulo, também o chunk de ARTIGO. Sem isso a
-- cerca cortaria a documentação inteira.
--
-- ── O que esta cerca NÃO cobre ──────────────────────────────────────────
-- Ela recusa arquivo INTERNO de outra base (o caso em que o custo do erro
-- deixa de ser "resposta errada" e passa a ser "documento interno de um
-- cliente exposto a outro"). Ela NÃO recusa uma documentação de ESPAÇO
-- que outra base anexou e esta não — pegar isso exigiria recalcular
-- elegibilidade aqui dentro, que é justamente o que esta cerca se recusa
-- a fazer. Esse caso continua coberto só pela aplicação
-- (`resolverEscopoDaBase`) e pela prova da tarefa 6.
--
-- ── O QUE SAIU DESTE ARQUIVO, E PARA ONDE FOI (tarefa 15) ──────────────
-- As definições de `public.hybrid_search_scoped` e de
-- `public.knowledge_list_chunks`, os `comment on function` das duas e as
-- assertivas que as CHAMAM saíram daqui e passaram a morar num sítio ÚNICO:
--
--   supabase/migrations/20260926120000_funcoes_de_escopo_canonicas.sql
--
-- Enquanto as duas estavam definidas aqui TAMBÉM, reaplicar este arquivo
-- sozinho — operação normal, porque não há ledger — desfazia em SILÊNCIO duas
-- correções posteriores da `20260925160000`:
--
--   · devolvia `from public.ai_bases` para a CTE `base_alvo` das duas funções,
--     que são SECURITY INVOKER. `anon` não tem grant em `ai_bases`, e a
--     permissão de tabela é conferida no INÍCIO da execução para toda entrada
--     da range table — então nem `p_base is null` salvava. A busca PÚBLICA do
--     portal morria com `permission denied for table ai_bases`, e
--     `searchPortal` engolia o erro como lista vazia. Ficou morta por horas em
--     25/09 exatamente assim;
--   · devolvia o `btrim` de UM argumento no lugar de
--     `public.codigo_normalizado`, reabrindo o furo do NBSP ENTRE CLIENTES: uma
--     base cujo código difere só por NBSP é linha DISTINTA para o índice único
--     e o MESMO valor para o motor de elegibilidade, então uma documentação
--     restrita a uma base alcançava os usuários da outra.
--
-- A assinatura das duas não mudou entre aqui e a 160000, então nem
-- `npm run verificar:rpc` nem a assertiva de assinatura percebiam: era o CORPO
-- que retrocedia. Agora `npm run verificar:corpo` recusa o segundo sítio.
--
-- ── O que FICOU, e por que ─────────────────────────────────────────────
-- Os dois `drop function if exists` das assinaturas ANTIGAS, que é o que este
-- arquivo fez de próprio: a transição de 7 para 8 parâmetros em
-- `hybrid_search_scoped` e de 3 para 4 em `knowledge_list_chunks`. Eles não
-- podem viajar para o arquivo canônico — `drop function` + `create` devolve
-- EXECUTE a PUBLIC, e nenhuma assinatura muda lá.
--
-- São idempotentes e inofensivos: hoje as assinaturas antigas não existem, e o
-- `if exists` faz deles no-op. Numa aplicação do zero eles continuam
-- necessários, porque os oito arquivos marcados `ARQUIVO SUPERADO` criam as
-- antigas antes daqui. E se alguém reaplicar um daqueles oito à mão, reaplicar
-- ESTE arquivo passa a ser o conserto: ele derruba a duplicata que deixa toda
-- chamada do app ambígua.
-- =====================================================================

drop function if exists public.hybrid_search_scoped(text, vector, uuid[], integer, uuid[], text, integer);

-- knowledge_list_chunks: o caminho de ENUMERAÇÃO ("todos os X de Y"), que
-- devolve até 40 chunks por documento em vez de 1 — o pior lugar para
-- deixar sem cerca, porque é o que mais despeja conteúdo no prompt.
drop function if exists public.knowledge_list_chunks(text, uuid[], integer);
