-- =====================================================================
-- A LINHA POR BASE VIRA SOBREPOSIÇÃO, E ELA SÓ ESTREITA
--
-- `public.escopo_documentacao` era `union` puro: o primeiro ramo devolvia
-- toda `documentacoes_universais` habilitada e elegível, o segundo devolvia
-- `ai_base_documentacoes` daquela base. União é OU, então a linha por base
-- só conseguia SOMAR — desligar não desligava, e regra mais estreita por
-- base não estreitava, porque o ramo mais frouxo ganhava.
--
-- A tela do cliente (`/gestao/conteudo`, tarefa 8) já está escrita
-- prometendo sobreposição, com os três estados Padrão · Ajustada · Oculta.
-- Esta migration é o lado do banco dessa promessa.
--
-- A semântica nova é a MESMA que o produto já usa para conteúdo de
-- documentação (`space_overlays`, com `hidden` e `override_article_id`):
--
--   · sem linha para (base, documentação)  → vale a universal, com a regra
--     da Natcorp. É o padrão, e é o "acessível de forma padrão por todas as
--     bases" da especificação;
--   · linha com `enabled = false`          → aquela documentação DESAPARECE
--     para os usuários daquela base;
--   · linha com `enabled = true` e `regra` → a pessoa precisa satisfazer AS
--     DUAS regras, a da Natcorp e a da base. INTERSEÇÃO, não substituição.
--
-- ── Por que INTERSEÇÃO e não substituição (decisão do dono, 25/09) ─────
-- Substituir deixaria um cliente ABRIR o que a Natcorp fechou: liberar para
-- a empresa inteira dele uma documentação que a Natcorp restringiu a um
-- portal. A especificação diz que a parametrização por portal existe "pois
-- existem documentações específicas para cada portal", então permitir
-- desfazê-la poria o manual do Operador na frente de um Colaborador — que é
-- precisamente o que a regra existe para evitar. E a postura deste projeto
-- inteiro é que o ramo mais frouxo ganhar é DEFEITO, não recurso: foi isso
-- que a tarefa 2 corrigiu em `chunks_write`, e reintroduzir aqui seria andar
-- para trás. A regra da Natcorp é TETO; o cliente só aperta.
--
-- Em SQL isso é `public.elegivel(u.regra, ident) and public.elegivel(d.regra,
-- ident)` — a MESMA função duas vezes, nenhuma segunda implementação da
-- regra. A assertiva 4 lá embaixo é a que PROVA esta decisão: ela falha se
-- alguém trocar interseção por substituição.
--
-- ── ENQUANTO EXISTIR LINHA UNIVERSAL, ELA É O TETO — inclusive desligada ──
-- O `not exists` do segundo ramo olha a EXISTÊNCIA da linha universal, não o
-- `enabled` dela. Consequência, que é decisão de semântica e está aqui para
-- quem vier depois não a descobrir por acidente:
--
--   universal com `enabled = false` + linha da base com `enabled = true`
--   → a documentação NÃO alcança ninguém.
--
-- É o teto levado às últimas: `enabled = false` na universal é teto ZERO, e
-- nenhuma linha de cliente reabre teto. É coerente com a trava da tela
-- (`estaNoPocoUniversal` exige `enabled = true` para o cliente poder criar a
-- sobreposição) e com a doutrina "o cliente só aperta".
--
-- Para devolver uma documentação ao controle POR BASE, o caminho é APAGAR a
-- linha de `documentacoes_universais`, não desligá-la: sem a linha, o
-- `not exists` passa e o anexo por base volta a valer. A assertiva 6 fixa
-- esse comportamento, e é o lugar de mexer se o dono decidir o contrário.
--
-- ── Para RETIRAR uma documentação que vem da CHAVE ─────────────────────
-- Não é aqui, e é a pergunta que a próxima pessoa vai fazer. O escopo da
-- chave (`widget_key_spaces`) passa a ser SEMPRE somado pelo lado da
-- aplicação (`decidirEscopo`, em `src/lib/ai/escopo-da-base.ts`), então
-- nenhuma configuração desta função remove uma documentação de chave. Para
-- retirar uma, remova-a onde ela é configurada — a tela da chave, em
-- `/admin/widget`. Isso é explícito e é da Natcorp. O cliente não tira
-- documentação de chave; ele só esconde universal.
--
-- ── `create or replace`, e NUNCA `drop function` aqui ──────────────────
-- A assinatura NÃO muda: `(text, jsonb)` entra e `(text, jsonb)` sai. Um
-- `drop function` + `create` devolveria EXECUTE a PUBLIC (portanto a `anon`)
-- e desfaria o revoke da migration 20260925100000. É o OPOSTO da tarefa 7,
-- onde a assinatura ganhou parâmetro e o drop era obrigatório para não
-- deixar duas funções de pé e toda chamada existente ficar ambígua.
-- Situação oposta, regra oposta.
--
-- ── `in (select …)` e não subconsulta escalar ──────────────────────────
-- Mesma razão da tarefa 7: `base_code` normalizado pode, em teoria, casar
-- mais de uma linha, e `(select id from alvo)` como escalar levantaria "more
-- than one row returned by a subquery used as an expression" — erro que
-- `rag.ts` engole, porque as chamadas desestruturam só `{ data }`. O índice
-- único de 20260925130000 fecha a porta, mas a função não depende dele.
--
-- ── O QUE SAIU DESTE ARQUIVO, E PARA ONDE FOI (tarefa 15) ──────────────
-- A definição de `public.escopo_documentacao(text, jsonb)`, o `comment on
-- function` dela, os `revoke`/`grant` e as seis assertivas que a CHAMAM saíram
-- daqui e passaram a morar num sítio ÚNICO:
--
--   supabase/migrations/20260926120000_funcoes_de_escopo_canonicas.sql
--
-- Enquanto ela estava definida aqui TAMBÉM, reaplicar este arquivo sozinho —
-- operação normal, porque não há ledger — desfazia em SILÊNCIO duas correções
-- da `20260925160000`: voltava o `lower(btrim(coalesce(p_base,'')))` de UM
-- caractere no lugar de `public.codigo_normalizado`, que apara os cinco brancos
-- de `public.allowlist_casa`, e devolvia o EXECUTE de `authenticated` numa
-- função `security definer` que ignora a RLS das quatro tabelas que lê —
-- qualquer Leitor deduzia a regra do dono variando a identidade.
--
-- A assinatura é `(text, jsonb)` nas duas, então nem `npm run verificar:rpc`
-- nem assertiva de assinatura nenhuma percebia: era o CORPO que retrocedia.
-- Agora `npm run verificar:corpo` recusa o segundo sítio.
--
-- ── Este arquivo passou a ser SÓ a DECISÃO ─────────────────────────────
-- O que sobrou aqui é o registro de POR QUE a sobreposição só estreita
-- (interseção, nunca substituição), por que a universal é teto mesmo desligada,
-- e por que retirar documentação de CHAVE não é aqui. Nada disso é DDL: o
-- arquivo aplica sem executar comando nenhum, e é de propósito. A migration que
-- CRIA a função é a canônica; esta é onde a semântica dela está justificada, e é
-- aqui que se discute mudá-la.
--
-- A assertiva 4 (a que prova a interseção) e a 6 (universal desligada é teto
-- zero) são as que travam essa decisão, e viajaram para o arquivo canônico
-- porque CHAMAM a função: numa aplicação do zero elas rodariam antes de a
-- função existir se tivessem ficado aqui.
-- =====================================================================
