-- =====================================================================
-- CHAVE QUE NÃO É DIMENSÃO PASSA A FECHAR
--
-- `elegivel` itera `jsonb_each(regra)` e trata qualquer chave como
-- dimensão. Medido em produção antes desta migration:
--
--   elegivel('{"dimensao_inexistente":["x"]}', '{}')                           -> false
--   elegivel('{"dimensao_inexistente":["x"]}', '{"dimensao_inexistente":"x"}') -> TRUE
--
-- O segundo caso abre. Ele não acontece hoje, porque a identidade é
-- montada a partir das doze chaves conhecidas e nunca carrega chave
-- estranha — mas "não acontece hoje" não é uma garantia, e este é o
-- ponto único que as RPCs dos projetos 1 a 3 vão chamar.
--
-- O motivo mais forte é o gêmeo: o predicado em TypeScript iterava a
-- lista fixa de dimensões e IGNORAVA chave desconhecida. Ignorar abre
-- sempre, inclusive no caso que mais vai acontecer, que é typo no nome
-- da dimensão (`centro_custos` no plural). Os dois lados fechando por
-- construção é o que torna a paridade verificável em vez de casual.
--
-- A lista das doze mora aqui e em src/lib/elegibilidade/dimensoes.ts. A
-- duplicação é real e é coberta pelo corpus compartilhado, que tem caso
-- de chave desconhecida: se alguém acrescentar uma dimensão em um lado
-- só, `npm run verificar:elegibilidade` acusa.
--
-- ── O QUE SAIU DESTE ARQUIVO, E PARA ONDE FOI (tarefa 16) ────────────
-- A definição de `public.elegivel(jsonb, jsonb)`, o `comment on function`
-- dela, os `revoke`/`grant` e as catorze assertivas que a CHAMAM saíram daqui
-- e passaram a morar num sítio ÚNICO:
--
--   supabase/migrations/20260924234000_dimensoes_elegibilidade.sql
--
-- Enquanto ela estava definida aqui TAMBÉM, reaplicar este arquivo sozinho —
-- operação normal, porque não há ledger — desfazia em SILÊNCIO duas correções
-- posteriores: devolvia a lista das doze para dentro do corpo como array
-- literal (matando a fonte única que `npm run verificar:elegibilidade` usa
-- para comparar as DUAS listas, e não só os casos escritos), e devolvia a
-- REGRA INTEIRA malformada ao comportamento de levantar exceção, que numa RPC
-- de listagem é um 500 onde devia haver negação.
--
-- A assinatura nunca mudou, então nem `npm run verificar:rpc` nem nenhuma
-- assertiva de assinatura enxergavam isso: era o CORPO que retrocedia.
-- `npm run verificar:corpo` é quem recusa o segundo sítio agora.
--
-- Este arquivo fica como REGISTRO DA DECISÃO — chave que não é dimensão passa
-- a fechar, e por que os dois lados fechando por construção é o que torna a
-- paridade verificável. O texto acima é o que vale; o SQL mudou de endereço.
-- =====================================================================
