-- =====================================================================
-- ARQUIVO DE BASE SÓ ENTRA NO RAG QUANDO ESTÁ `ready`
--
-- ── O defeito, e por que ele é latente e não visível ──────────────────
-- `src/lib/ai/rag.ts` filtra `.eq("status", "ready")` nos arquivos que vêm
-- dos ESPAÇOS, e a justificativa está escrita logo acima da consulta:
-- documento ainda em extração tem chunks pela METADE, e responder com meia
-- planilha é pior do que não responder — o modelo não tem como saber que a
-- lista que ele recebeu está truncada, então ele afirma o parcial como se
-- fosse o todo.
--
-- `public.documentos_da_base` não tinha esse predicado, e `rag.ts` soma o
-- resultado dela aos arquivos dos espaços sem conferir. Medido em 26/09: os
-- 123 `knowledge_documents` de produção estão TODOS em `ready`, e nenhum
-- deles tem `base_id` — ou seja, hoje não há uma única linha que exercite o
-- caminho. É por isso que o defeito nunca apareceu, e é também por isso que
-- ele acorda no PRIMEIRO upload grande de cliente, que é exatamente o caso
-- de uso do pedido do dono: enquanto o worker extrai um PDF de 2.000
-- páginas, o chatbot daquele cliente responde com o pedaço que já entrou.
--
-- ── Por que o predicado vai AQUI, no SQL, e não na aplicação ──────────
-- Dois motivos, e o segundo é o que decide:
--
--   · este é o lugar onde o escopo por base MORA. Todo chamador presente e
--     futuro de `documentos_da_base` ganha o filtro de graça — inclusive o
--     próximo, que não vai ler o comentário de `rag.ts`;
--   · um filtro do lado da aplicação seria um SEGUNDO lugar para alguém
--     esquecer, e esquecer um segundo lugar é literalmente o defeito que
--     está sendo corrigido aqui. O predicado dos espaços já existia em
--     `rag.ts` e a função nova nasceu sem ele.
--
-- O status de extração é propriedade do ARQUIVO, não da tela que o consome.
-- Uma função que responde "quais arquivos desta base esta identidade
-- alcança" não deve devolver arquivo que não está pronto para ser lido.
--
-- ── O que NÃO muda ───────────────────────────────────────────────────
-- A tela de administração não usa esta função: ela lista os arquivos da base
-- direto da tabela (`src/lib/documentacoes/arquivos-da-base.ts`), e continua
-- mostrando `queued`/`extracting`/`error` com o estado de cada um — é
-- exatamente onde o dono precisa ver que a extração está em curso. O que
-- muda é só o que o RAG recebe.
--
-- `create or replace`: a assinatura é a MESMA (text, jsonb), então `drop` é
-- proibido aqui — `drop function` + `create` devolveria EXECUTE a PUBLIC, e
-- esta função é `security definer` sobre quatro tabelas.
--
-- ── O TERCEIRO SÍTIO FOI FECHADO (tarefa 15) ──────────────────────────
-- Quando este arquivo foi escrito, `public.documentos_da_base(text, jsonb)`
-- tinha TRÊS sítios de definição — `20260925110000`, `20260925160000` e este —
-- e a consolidação ficou anotada aqui como tarefa separada, para o dono
-- decidir. Ela foi feita: a definição, o `comment on function`, os
-- `revoke`/`grant` e a assertiva de `status` saíram daqui e passaram a morar num
-- sítio ÚNICO:
--
--   supabase/migrations/20260926120000_funcoes_de_escopo_canonicas.sql
--
-- O corpo de lá é a transcrição literal de `pg_get_functiondef` do banco de
-- produção, isto é, EXATAMENTE o corpo que este arquivo deixou vivo — com o
-- `k.status = 'ready'` que ele acrescentou. Foi conferido por SHA-256 antes e
-- depois de aplicar, e o digesto não mudou.
--
-- Este arquivo ficou sendo o registro da DECISÃO: por que arquivo em extração
-- não pode chegar ao RAG, e por que o predicado mora no SQL e não na aplicação.
-- Não executa comando nenhum, e é de propósito.
-- =====================================================================
